package coder.dasu.meizi.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import coder.dasu.meizi.data.bean.Meizi;
import coder.dasu.meizi.data.bean.Data;
import coder.dasu.meizi.data.bean.DayPublish;

import coder.dasu.meizi.data.dao.MeiziDao;
import coder.dasu.meizi.data.dao.DataDao;
import coder.dasu.meizi.data.dao.DayPublishDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig meiziDaoConfig;
    private final DaoConfig dataDaoConfig;
    private final DaoConfig dayPublishDaoConfig;

    private final MeiziDao meiziDao;
    private final DataDao dataDao;
    private final DayPublishDao dayPublishDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        meiziDaoConfig = daoConfigMap.get(MeiziDao.class).clone();
        meiziDaoConfig.initIdentityScope(type);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        dayPublishDaoConfig = daoConfigMap.get(DayPublishDao.class).clone();
        dayPublishDaoConfig.initIdentityScope(type);

        meiziDao = new MeiziDao(meiziDaoConfig, this);
        dataDao = new DataDao(dataDaoConfig, this);
        dayPublishDao = new DayPublishDao(dayPublishDaoConfig, this);

        registerDao(Meizi.class, meiziDao);
        registerDao(Data.class, dataDao);
        registerDao(DayPublish.class, dayPublishDao);
    }
    
    public void clear() {
        meiziDaoConfig.clearIdentityScope();
        dataDaoConfig.clearIdentityScope();
        dayPublishDaoConfig.clearIdentityScope();
    }

    public MeiziDao getMeiziDao() {
        return meiziDao;
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public DayPublishDao getDayPublishDao() {
        return dayPublishDao;
    }

}
