package coder.dasu.meizi.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import coder.dasu.meizi.data.bean.User;
import coder.dasu.meizi.data.bean.Meizi;

import coder.dasu.meizi.data.dao.UserDao;
import coder.dasu.meizi.data.dao.MeiziDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig meiziDaoConfig;

    private final UserDao userDao;
    private final MeiziDao meiziDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        meiziDaoConfig = daoConfigMap.get(MeiziDao.class).clone();
        meiziDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        meiziDao = new MeiziDao(meiziDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Meizi.class, meiziDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        meiziDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MeiziDao getMeiziDao() {
        return meiziDao;
    }

}
