package coder.dasu.meizi.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import coder.dasu.meizi.data.bean.Meizi;
import coder.dasu.meizi.data.bean.GankDayHistory;

import coder.dasu.meizi.data.dao.MeiziDao;
import coder.dasu.meizi.data.dao.GankDayHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig meiziDaoConfig;
    private final DaoConfig gankDayHistoryDaoConfig;

    private final MeiziDao meiziDao;
    private final GankDayHistoryDao gankDayHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        meiziDaoConfig = daoConfigMap.get(MeiziDao.class).clone();
        meiziDaoConfig.initIdentityScope(type);

        gankDayHistoryDaoConfig = daoConfigMap.get(GankDayHistoryDao.class).clone();
        gankDayHistoryDaoConfig.initIdentityScope(type);

        meiziDao = new MeiziDao(meiziDaoConfig, this);
        gankDayHistoryDao = new GankDayHistoryDao(gankDayHistoryDaoConfig, this);

        registerDao(Meizi.class, meiziDao);
        registerDao(GankDayHistory.class, gankDayHistoryDao);
    }
    
    public void clear() {
        meiziDaoConfig.clearIdentityScope();
        gankDayHistoryDaoConfig.clearIdentityScope();
    }

    public MeiziDao getMeiziDao() {
        return meiziDao;
    }

    public GankDayHistoryDao getGankDayHistoryDao() {
        return gankDayHistoryDao;
    }

}
